#!/usr/bin/env python

import subprocess

n = 100

count = 0
for i in range(n):
	res = subprocess.check_output(["./ml_por", "a.param"])
	#print(res)
	if(res.find("equal", 0, len(res)) != -1):
		# equals
		count += 1
	else:
		print("Failed at iteraction no. " + str(i))

print("Worked: " + str(count) + "/" + str(n) + " (" + str(100.0*(0.0+count)/n) + "%)")
