#!/usr/bin/env python

import subprocess

# EDIT THIS VALUE TO CHANGE NUMBER OF EXECUTIONS
num = 10

# success = False
count = 0
for i in range(num): #while(success == False):
	res = subprocess.check_output(['./ml_por', 'a.param'])
	key1 = res.split("FINAL KEY (HASED): ")[1].split()[0]
	key2 = res.split("FINAL KEY (HASED): ")[2].split()[0]
	print("comparing keys: \n1) "+key1+"\n2) "+key2+"\n")
	if(key1 == key2): #if(res.find("equal", 0, len(res)) != -1):
		count += 1 #success = True
print("Worked: "+str(count)+"/"+str(num)+" ("+str(100.0*(0.0+count)/num)+"%)")
