#!/usr/bin/env python

import subprocess

success = False
while(success == False):
	res = subprocess.check_output(['./ml_por', 'a.param'])
	if(res.find("equal", 0, len(res)) != -1):
		success = True
print(res)
