#!/usr/bin/env python

import subprocess

num = 100

# success = False
count = 0
for i in range(num): #while(success == False):
	res = subprocess.check_output(['./ml_por', 'a.param'])
	if(res.find("equal", 0, len(res)) != -1):
		count += 1 #success = True
print("Worked: "+str(count)+"/"+str(num)+" ("+str(100.0*(0.0+count)/num)+"%)")
